# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Abubakkar Siddique
title: Summer Intern
email: abubakkarsid415@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: Abubakk62549788
github_username:  abubakkar13
instagram_username: abubakkar.siddique_
linkedin_username: abubakkar-siddique-21b9351b2
youtube_username: UC6UBKR1ZQ8bN3YxiKkeKO-g
medium_username: abubakkarsid415

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
#about_profile_image: /main/pic.jpeg
about_content: | # this will include new lines to allow paragraphs
  This is Abubakkar Siddique, a student, programmer and with Problem Solving Skills. Fond of Knowledge and Data repositories. Adept in making key decisions and working with other professionals to achieve goals and solve problems.
  
  Committed to utilizing my skills to further the Task completion. Well-rounded and professional team player dedicated to continuing academic pursuits at a collegiate level.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Awesome project on Data Analysis
        link: https://abubakkar13.github.io/notebookview.html
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://abubakkar13.github.io/
        quote: >
          This is probably one of the greatest project ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning *Python* and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Goalstreet
        link: https://www.mygoalstreet.com
        sub_title: Summer Intern
        domain: Machine Learning with Python
        caption: August 2020 - October 2020
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            A team of enthusiasts who act as quantification instruments in assessing the abilities and imparting technical and interpersonal skills in students that are required in today's competitive market through our distinct methodologies
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Visvesvaraya Technological University
        caption: 2017 - 2021
        sub_title: BE - Computer Science and Engineering
        quote: >
          Visvesvaraya Technological University (VTU, previously spelled "Visveswaraiah Technological University") is a collegiate public state university in Belagavi, Karnataka established by the Government of Karnataka.[10] Apart from a few notable exceptions, VTU has authority over engineering education throughout the state of Karnataka. It is a statutory requirement for colleges offering any program in engineering or technology in the state to be affiliated with the university. The university is named after M. Visvesvaraya from Karnataka, the only engineer to be awarded a Bharat Ratna, the highest civilian award in India.
        description: | # this will include new lines to allow paragraphs
          During my time at College I learnt most of my key skills that have I have taken through my career such as coding, problem solving and learned all required concepts. I thouroughly enjoyed my time as university and learnt a lot of Good things.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Coding and Problem Solving some of my other interests and hobbies are:
      - Cricket
      - Gaming
      - Internet Exploring
      - Enthusiast of Becoming a Data Analyst

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
